FROM quay.io/centos/centos:stream9

COPY files/cm.repo /etc/yum.repos.d/cm.repo
COPY files/RPM-GPG-KEY-cm /etc/pki/rpm-gpg/

COPY files/start_cmd.sh /usr/local/bin/start_cmd.sh

# EPEL is required for slurm dependencies
RUN dnf install -y cmdaemon procps-ng epel-release && dnf clean all

# Slurm stuff to pass health checks
RUN dnf install -y epel-release slurm24.05 slurm24.05-client slurm24.05-contribs slurm24.05-devel slurm24.05-perlapi slurm24.05-slurmdbd && dnf clean all

# Debugging
RUN dnf install -y iputils net-tools psmisc nano && dnf clean all

# stuff to pass bcm Health check
RUN dnf install -y iproute nfs-utils && dnf clean all
RUN useradd -m cmsupport
# RUN gpasswd -a cmsupport wheel

RUN sed -i 's/master/slave/' /etc/cm-release
